import { ReactNode } from 'react'
import './globals.css'
import { Roboto } from 'next/font/google'
import { Session } from 'next-auth'
import { GoogleProvider } from './providers'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
})

export const metadata = {
  title: 'Ignite Call',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session,
}: {
  children: ReactNode
  session: Session
}) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <GoogleProvider session={session}>{children}</GoogleProvider>
      </body>
    </html>
  )
}
